### ISSUE TITLE
Using iFrames with Flask

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/tesla-ver#41]
Look into using iFrames to incorporate the plotly graph, dash, and the Flask server

**Comment by alexanderkyim** [comment]
Having looked at this, it looks as though it basically requires there to be a second server to run the dash app, which would make passing data from analysis to server much more difficult.  Basically, this technique would make #39, #40, and #42 much trickier than just doing this with flask as the server to embed and serve the dash app.
