### ISSUE TITLE
Data format between Tesla-ver and Loclust

### ISSUE THREAD

**Issue by alexanderkyim** [clemente-lab/tesla-ver#49]
Currently, Tesla-ver parses a group of loclust trajectory files into a single dataframe that's then used to render the graph.

Providing interoperability with loclust would be useful, as is shifting it to apply to a single data file with multiple trajectories (a truly 3D or greater dataset, compared to the 2D data files it's being tested with right now).

Mostly this issue exists to document and open a discussion on which data tesla-ver is supposed to be used, and how the data is then stored and handled internally.

**Comment by DSWallach** [comment]
Here are some examples of the type of mutli-variable data we want to visualize. Each subject has abundance values from multiple bacteria at each time point. There are three different dataset sizes for performance testing. Github won't let me upload .tsv so they have the .txt extension but they're tab separated.
[tesla_data_10.txt](https://github.com/clemente-lab/tesla-ver/files/4826524/tesla_data_10.txt)
[tesla_data_100.txt](https://github.com/clemente-lab/tesla-ver/files/4826525/tesla_data_100.txt)
[tesla_data_1000.txt](https://github.com/clemente-lab/tesla-ver/files/4826526/tesla_data_1000.txt)

**Comment by alexanderkyim** [comment]
Thank you, these look great!
